Repository ViewTouch/viewtouch, pull requests merged in 2025-06, with the labels that each got.

#151 Update vt_data download url from http to https
  CMakeLists.txt
  main/manager.cc
Labels: bug

#159 manager.cc: fix download URLs for bootstrap dat files
  changelog.md
  main/manager.cc
  tests/main/manager_stub.cc
Labels: bug

#163 cmake: gen_compiler_tag: fix exec_program and add clang version
  changelog.md
  cmake/gen_compiler_tag.cmake
Labels: maintenance

#164 cmake: fix deprecation warning, CMake 4.0+ compatibility
  CMakeLists.txt
  changelog.md
Labels: maintenance

#161 Moving from bitmapped fonts to scalable outline fonts
  SCALABLE_FONTS_MIGRATION.md
  loader/loader_main.cc
  term/layer.cc
  term/term_credit_cheq.cc
  term/term_credit_mcve.cc
  term/term_dialog.cc
  term/term_main.cc
  term/term_view.cc
  term/term_view.hh
  term/touch_screen.cc
  tests/main/manager_stub.cc
Labels: Enhancement
